#pragma once

namespace QLogicaeQtStaticLibrary
{
	#ifndef BUILD_STATIC
	# if defined(QLOGICAE_QT_STATIC_LIBRARY_APPLICATION_LIB)
	#  define QLOGICAE_QT_STATIC_LIBRARY_APPLICATION_EXPORT Q_DECL_EXPORT
	# else
	#  define QLOGICAE_QT_STATIC_LIBRARY_APPLICATION_EXPORT Q_DECL_IMPORT
	# endif
	#else
	# define QLOGICAE_QT_STATIC_LIBRARY_APPLICATION_EXPORT
	#endif
}
