#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(QLOGICAE_VS2022_QT_DYNAMICALLY_LINKED_LIBRARY_LIB)
#  define QLOGICAE_VS2022_QT_DYNAMICALLY_LINKED_LIBRARY_EXPORT Q_DECL_EXPORT
# else
#  define QLOGICAE_VS2022_QT_DYNAMICALLY_LINKED_LIBRARY_EXPORT Q_DECL_IMPORT
# endif
#else
# define QLOGICAE_VS2022_QT_DYNAMICALLY_LINKED_LIBRARY_EXPORT
#endif
